# Generated by Django 4.0.6 on 2022-07-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_account_card_notification_receipt_thirdparty_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
