# Generated by Django 4.0.6 on 2022-07-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_account_password_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
