# Generated by Django 4.0.6 on 2022-07-31 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
