# Generated by Django 4.0.6 on 2022-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_notification_date_and_time_notification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
