# Generated by Django 4.0.6 on 2022-07-31 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_loan_loan_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='Transaction',
            new_name='transaction',
        ),
        migrations.AddField(
            model_name='card',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='date_issue',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanbalance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanterm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='payduedate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='Customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='Phone_number',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_b', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_a', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactiondateandtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
